
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[282] =
    {   0,
        0,    0,  100,   98,   97,   96,   96,   53,   98,   98,
       60,   77,   98,   47,   48,   61,   57,   46,   58,   76,
       59,   33,   33,   52,   51,   65,   64,   66,   55,   92,
       92,   50,   43,   49,   56,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   44,   78,   45,   54,   70,    0,   93,    0,
        0,    0,    0,   75,   80,   85,    0,    0,   95,    0,
       73,   62,   71,   63,   72,   79,    0,   41,    0,    0,
       74,   42,   33,   98,   98,   38,   98,   33,   89,   67,
       69,   68,   88,   92,    0,   43,   86,   92,   92,   92,

       92,   92,   92,   92,    8,   92,   92,   92,   92,   92,
       92,   16,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   87,   81,   94,    0,    0,    0,   94,
        0,    0,    0,   39,   82,    0,   41,    0,    0,    0,
       35,   41,    0,   42,   37,   98,    0,   40,   38,   36,
       84,   83,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   14,   92,   17,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,    0,    0,   93,    0,    0,    0,    0,   41,   34,
        0,   41,    0,   42,   37,   40,   40,   36,    1,   92,

        3,    4,   92,   92,   92,   92,   10,   11,   92,   92,
       15,   18,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   30,   92,   92,    0,    0,    0,   41,
       40,    2,    5,   92,   92,   92,   92,   13,   92,   92,
       21,   92,   92,   92,   92,   92,   92,   28,   92,   92,
       32,    0,    0,   92,   92,    9,   12,   92,   20,   22,
       23,   24,   25,   26,   92,   92,   92,   91,    0,   92,
        7,   92,   27,   92,   92,   90,    6,   19,   29,   31,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   31,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    3,
        3,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[292] =
    {   0,
        0,    0,  465,  466,  466,  466,  466,  439,   61,   67,
      438,   60,   68,  466,  466,  437,   58,  466,   61,   56,
       70,   98,   70,  466,  466,   56,  436,   67,  466,    0,
      449,  466,   97,  466,  434,    0,  400,  402,   58,   64,
       72,   56,  403,   30,  402,  410,   78,  391,  400,  398,
      403,    0,  466,   69,  466,  466,  466,  100,  466,  134,
      138,  405,  396,  466,  466,  466,  110,  136,  466,  444,
      466,  466,  466,  466,  466,  466,  428,  134,  431,  441,
      466,  153,  155,    0,  174,  119,  194,    0,  418,  466,
      466,  466,  417,    0,  154,  466,  466,    0,  384,  396,

      383,  398,  385,  391,  377,  378,  375,  375,  378,  375,
      372,    0,  371,  375,   66,  373,   98,  152,  377,  370,
      102,  151,  375,  466,  466,  466,  164,  173,  189,  195,
      205,  377,  379,  466,  466,  212,  466,  406,  192,  416,
      466,  222,  229,  466,  215,    0,  196,  238,  224,  228,
      466,  466,  365,  377,  372,  360,  162,  374,  372,  368,
      360,  366,  369,    0,  355,    0,  361,  358,  347,  349,
      351,  358,  344,  342,  342,  354,  344,  348,  352,  354,
      343,  219,  268,  233,  273,  344,  341,  200,  269,  466,
      264,  466,  242,  273,  263,  290,    0,  274,    0,  341,

        0,    0,  332,  340,  329,  336,    0,    0,  330,  327,
        0,    0,  327,  327,  324,  336,  326,  297,  302,  301,
      299,  287,  292,    0,  280,  292,  282,  275,  271,  296,
      466,    0,    0,  279,  280,  285,  275,    0,  268,  263,
        0,  269,  263,  260,  243,  251,  253,    0,  235,  229,
        0,  220,  210,  187,  173,    0,    0,  184,    0,    0,
        0,    0,    0,    0,  165,  160,  143,  466,  124,  105,
        0,   90,    0,   86,   52,  466,    0,    0,    0,    0,
      466,  346,  350,  353,  354,  356,  360,  364,  368,  370,
      374

    } ;

static yyconst flex_int16_t yy_def[292] =
    {   0,
      281,    1,  281,  281,  281,  281,  281,  281,  282,  281,
      281,  281,  283,  281,  281,  281,  281,  281,  281,  281,
      281,  284,  284,  281,  281,  281,  281,  281,  281,  285,
      285,  281,  281,  281,  281,  286,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  281,  281,  281,  281,  281,  282,  281,  287,
      281,  281,  281,  281,  281,  281,  283,  283,  281,  283,
      281,  281,  281,  281,  281,  281,  281,  281,  288,  289,
      281,  281,   23,  290,  290,  290,  290,   23,  281,  281,
      281,  281,  281,  285,  283,  281,  281,  286,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  281,  281,  281,  291,  282,  282,  282,
      291,  281,  281,  281,  281,  281,  281,  288,  288,  289,
      281,  281,  281,  281,  290,  290,  281,  290,  290,   87,
      281,  281,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  282,  291,  282,  287,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  290,  281,  290,  290,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  281,  281,  281,  281,
      281,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  281,  281,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  281,  281,  285,
      285,  285,  285,  285,  285,  281,  285,  285,  285,  285,
        0,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281

    } ;

static yyconst flex_uint16_t yy_nxt[534] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   30,   30,
       30,   31,   30,   30,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   30,   44,   30,   45,
       30,   30,   30,   30,   46,   47,   48,   49,   50,   51,
       30,   30,   52,   53,   54,   55,   56,   59,   61,   65,
       68,   61,   72,   77,  112,   78,   78,   74,   69,   89,
       90,  113,   73,   79,   66,   75,   76,   82,   80,   88,
       88,   92,   93,  124,   81,  280,   60,  101,   85,   96,

       96,   86,   86,   70,  102,  109,  126,  104,  110,   62,
      103,  168,   68,   85,   63,   82,  105,   83,   83,   86,
      134,  106,  169,  107,  116,  117,   85,   86,  279,   86,
       86,   87,  108,  125,  118,  127,  129,  119,   68,   61,
      130,   85,   61,  171,  278,   70,  134,   86,  277,  177,
      149,  149,   96,   78,   78,   86,   68,  178,   87,   96,
      172,   96,  136,  137,   69,  137,   58,  276,  149,  131,
      130,   70,  142,  142,   83,   83,  149,  136,  137,   59,
       62,  143,  144,  137,  144,   63,  145,  145,  147,   70,
      147,  173,  275,  148,  148,   59,  143,  144,  179,  183,

      180,  126,  144,  274,  145,  139,  174,   58,   60,  273,
      190,  184,  145,  150,  150,  196,  196,  203,  204,  189,
      189,  150,  150,  150,   60,  126,  188,  272,  188,  271,
      127,  189,  189,  150,  150,  150,  150,  150,  150,  126,
      185,  142,  142,  193,  270,  193,  195,  195,  194,  194,
      191,  192,  269,  192,  127,  149,  149,  148,  148,  198,
      198,  194,  194,  268,  195,  191,  192,  197,  127,  197,
       58,  192,  195,  149,  130,  129,  267,  198,  229,  130,
      229,  149,  197,  230,  230,  198,  266,  197,  189,  189,
      230,  230,  194,  194,  195,  195,  265,  264,  137,  263,

      137,  262,  144,  183,  144,  198,  198,  261,  131,  196,
      196,  260,  195,  137,  259,  230,  230,  144,  137,  231,
      195,  231,  144,  198,  258,  192,  257,  192,  256,  255,
      254,  198,  253,  252,  231,  251,  250,  249,  248,  231,
      192,  247,  246,  245,  244,  192,   58,   58,   58,   58,
       67,   67,   67,   67,   84,   84,   94,   94,   98,   98,
      128,  128,  128,  128,  138,  138,  138,  138,  140,  140,
      140,  140,  146,  146,  182,  182,  182,  182,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,

      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  202,  201,  200,  199,  141,  139,
      187,  186,  181,  176,  175,  170,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  141,  139,  135,  281,  133,  132,  123,
      122,  121,  120,  115,  114,  111,  100,   99,   97,   95,
       91,   71,   64,   57,  281,    3,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

static yyconst flex_int16_t yy_chk[534] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,   10,   12,
       13,   10,   17,   20,   44,   20,   20,   19,   13,   26,
       26,   44,   17,   21,   12,   19,   19,   23,   21,   23,
       23,   28,   28,   54,   21,  275,    9,   39,   23,   33,

       33,   23,   23,   13,   39,   42,   58,   40,   42,   10,
       39,  115,   67,   23,   10,   22,   40,   22,   22,   23,
       67,   41,  115,   41,   47,   47,   22,   23,  274,   22,
       22,   22,   41,   54,   47,   58,   60,   47,   68,   61,
       60,   22,   61,  117,  272,   67,   68,   22,  270,  121,
       86,   86,   33,   78,   78,   22,   95,  121,   22,   33,
      117,   33,   78,   78,   95,   78,  127,  269,   86,   60,
      127,   68,   82,   82,   83,   83,   86,   78,   78,  128,
       61,   82,   82,   78,   82,   61,   83,   83,   85,   95,
       85,  118,  267,   85,   85,  129,   82,   82,  122,  127,

      122,  130,   82,  266,   83,  139,  118,  131,  128,  265,
      139,  131,   83,   87,   87,  147,  147,  157,  157,  188,
      188,   87,   87,   87,  129,  182,  136,  258,  136,  255,
      130,  136,  136,   87,   87,   87,   87,   87,   87,  184,
      131,  142,  142,  143,  254,  143,  145,  145,  143,  143,
      142,  142,  253,  142,  182,  149,  149,  148,  148,  150,
      150,  193,  193,  252,  145,  142,  142,  148,  184,  148,
      183,  142,  145,  149,  183,  185,  250,  150,  191,  185,
      191,  149,  148,  191,  191,  150,  249,  148,  189,  189,
      229,  229,  194,  194,  195,  195,  247,  246,  189,  245,

      189,  244,  194,  183,  194,  198,  198,  243,  185,  196,
      196,  242,  195,  189,  240,  230,  230,  194,  189,  196,
      195,  196,  194,  198,  239,  230,  237,  230,  236,  235,
      234,  198,  228,  227,  196,  226,  225,  223,  222,  196,
      230,  221,  220,  219,  218,  230,  282,  282,  282,  282,
      283,  283,  283,  283,  284,  284,  285,  285,  286,  286,
      287,  287,  287,  287,  288,  288,  288,  288,  289,  289,
      289,  289,  290,  290,  291,  291,  291,  291,  217,  216,
      215,  214,  213,  210,  209,  206,  205,  204,  203,  200,
      187,  186,  181,  180,  179,  178,  177,  176,  175,  174,

      173,  172,  171,  170,  169,  168,  167,  165,  163,  162,
      161,  160,  159,  158,  156,  155,  154,  153,  140,  138,
      133,  132,  123,  120,  119,  116,  114,  113,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   93,   89,   80,   79,   77,   70,   63,   62,   51,
       50,   49,   48,   46,   45,   43,   38,   37,   35,   31,
       27,   16,   11,    8,    3,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "myscanner.l"
#line 2 "myscanner.l"
//#include "myscanner.h"
#include "parser.tab.h"
void yyerror(char *);
int linea = 1;
int endline;
int fdefine=1;
char* gramaticas[500000];


#line 691 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "myscanner.l"


#line 912 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 282 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 466 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return AUTO;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return BREAK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CASE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONST;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONTINUE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DEFAULT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DOUBLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return ENUM;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return EXTERN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return FOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return GOTO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return INT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LONG;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return REGISTER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RETURN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SHORT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SIGNED;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SIZEOF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return STATIC;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return STRUCT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SWITCH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return TYPEDEF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return UNION;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return UNSIGNED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return VOID;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return VOLATILE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return INTEGER;}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 50 "myscanner.l"

	YY_BREAK
case 35:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 51 "myscanner.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 56 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return CONSTANT;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 61 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SLASH;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LEFT_BRACKET;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RIGHT_BRACKET;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return COMMA;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LEFT_PARENTHESIS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RIGHT_PARENTHESIS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RIGHT_SBRACKET;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 68 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LEFT_SBRACKET;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SEMICOLON;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return COLON;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return EXCLAMATION;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return PRIME;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return INTERROGATION;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 74 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return UP_ARROW;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 75 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return PLUS;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 76 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return MINUS;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 77 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DIV;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 78 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return MOD;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 79 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return MUL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 80 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return INC_OP;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 81 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DEC_OP;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 82 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return EQU;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 83 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LESS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 84 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return GREATER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 85 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LE_OP;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 86 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return GE_OP;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return EQ_OP;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return NE_OP;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return ADD_ASSIGN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return SUB_ASSIGN;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return MUL_ASSIGN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DIV_ASSIGN;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 93 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return MOD_ASSIGN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 94 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return DOT;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 95 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return BIT_AND;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 96 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return BIT_OR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 97 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return PTR_OP;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 98 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return AND_OP;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 99 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return OR_OP;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 100 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return ELLIPSIS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 101 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RIGHT_ASSIGN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 102 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LEFT_ASSIGN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 103 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return AND_ASSIGN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 104 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return XOR_ASSIGN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 105 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return OR_ASSIGN;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 106 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return RIGHT_OP;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 107 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LEFT_OP;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 109 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return INCLUDE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 110 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");fdefine=0;return DEFINE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 111 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return IDENTIFIER;}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 112 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LITERAL;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 113 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LITERAL;}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 115 "myscanner.l"
{strcat(gramaticas,yytext);strcat(gramaticas," ");return LITERAL;}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 116 "myscanner.l"
{linea++;endline=0;/*ignore*/;if(fdefine==0){fdefine=1;return ('\n');}else{fdefine=1;}}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 119 "myscanner.l"

	YY_BREAK
case 98:
YY_RULE_SETUP
#line 121 "myscanner.l"
yyerror(yytext);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 124 "myscanner.l"
ECHO;
	YY_BREAK
#line 1475 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 282 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 282 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 281);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 124 "myscanner.l"



int yywrap(void)
{
    return 1;
}

